// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using barberBoss.Infrastructure.DataBaseAcess;

#nullable disable

namespace barberBoss.Infrastructure.Migrations
{
    [DbContext(typeof(BarberBossDbContext))]
    partial class BarberBossDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("barberBoss.Domain.Entities.Billing", b =>
                {
                    b.Property<int>("IdBilling")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdBilling"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("BarberName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<Guid>("BillingIdentifier")
                        .HasColumnType("char(36)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IdBilling");

                    b.ToTable("Billings");

                    b.HasData(
                        new
                        {
                            IdBilling = 1,
                            Amount = 35.00m,
                            BarberName = "Kauê Olympio",
                            BillingIdentifier = new Guid("5a01af9c-9576-4a2a-bd45-277cb26c2d6f"),
                            ClientName = "Lucas Pereira",
                            CreatedAt = new DateTime(2025, 9, 1, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Pix",
                            ServiceName = "Corte",
                            Status = "Paid"
                        },
                        new
                        {
                            IdBilling = 2,
                            Amount = 25.00m,
                            BarberName = "Kauê Olympio",
                            BillingIdentifier = new Guid("b0f241ef-9aee-40d9-8f7a-2992e91dbcf2"),
                            ClientName = "Ruan Fernandes",
                            CreatedAt = new DateTime(2025, 9, 2, 14, 45, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Money",
                            ServiceName = "Barba",
                            Status = "Paid"
                        },
                        new
                        {
                            IdBilling = 3,
                            Amount = 60.00m,
                            BarberName = "Kauê Olympio",
                            BillingIdentifier = new Guid("e753d40e-e498-4187-89c8-ca40dd724629"),
                            ClientName = "Pedro Oliveira",
                            CreatedAt = new DateTime(2025, 9, 3, 9, 10, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "DebitCard",
                            ServiceName = "Corte e Barba",
                            Status = "Paid"
                        },
                        new
                        {
                            IdBilling = 4,
                            Amount = 35.00m,
                            BarberName = "Kauê Olympio",
                            BillingIdentifier = new Guid("e3df1d06-f377-4734-9714-dfafe4e6a20c"),
                            ClientName = "Gabriel Lima",
                            CreatedAt = new DateTime(2025, 9, 4, 13, 20, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "DebitCard",
                            ServiceName = "Corte",
                            Status = "Paid"
                        },
                        new
                        {
                            IdBilling = 5,
                            Amount = 60.00m,
                            BarberName = "Kauê Olympio",
                            BillingIdentifier = new Guid("9cf11b7a-27ed-4f67-b61e-03cbb4c0efb8"),
                            ClientName = "João Vitor",
                            CreatedAt = new DateTime(2025, 9, 5, 11, 50, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Pix",
                            ServiceName = "Corte e Barba",
                            Status = "Paid"
                        },
                        new
                        {
                            IdBilling = 6,
                            Amount = 25.00m,
                            BarberName = "Kauê Olympio",
                            BillingIdentifier = new Guid("91c0f9db-2ee1-406e-9b44-ac9235d12380"),
                            ClientName = "André Santos",
                            CreatedAt = new DateTime(2025, 9, 6, 16, 25, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Pix",
                            ServiceName = "Barba",
                            Status = "Paid"
                        },
                        new
                        {
                            IdBilling = 7,
                            Amount = 35.00m,
                            BarberName = "Kauê Olympio",
                            BillingIdentifier = new Guid("c2854470-71f5-431d-a002-aedf6f67652d"),
                            ClientName = "Felipe Rocha",
                            CreatedAt = new DateTime(2025, 9, 7, 12, 5, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Pix",
                            ServiceName = "Corte",
                            Status = "Paid"
                        },
                        new
                        {
                            IdBilling = 8,
                            Amount = 60.00m,
                            BarberName = "Kauê Olympio",
                            BillingIdentifier = new Guid("291060c6-445e-4d94-89fc-e4c20bc96803"),
                            ClientName = "Matheus Almeida",
                            CreatedAt = new DateTime(2025, 9, 8, 17, 40, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Pix",
                            ServiceName = "Corte e Barba",
                            Status = "Paid"
                        },
                        new
                        {
                            IdBilling = 9,
                            Amount = 35.00m,
                            BarberName = "Kauê Olympio",
                            BillingIdentifier = new Guid("e2136411-4a51-473f-a267-bfd219ffd419"),
                            ClientName = "Carlos Eduardo",
                            CreatedAt = new DateTime(2025, 9, 9, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Pix",
                            ServiceName = "Corte",
                            Status = "Paid"
                        },
                        new
                        {
                            IdBilling = 10,
                            Amount = 25.00m,
                            BarberName = "Kauê Olympio",
                            BillingIdentifier = new Guid("e9dedf56-1c77-4f29-b566-473693ed9c7a"),
                            ClientName = "Renan Silva",
                            CreatedAt = new DateTime(2025, 9, 10, 11, 10, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Pix",
                            ServiceName = "Barba",
                            Status = "Paid"
                        },
                        new
                        {
                            IdBilling = 11,
                            Amount = 35.00m,
                            BarberName = "Kauê Olympio",
                            BillingIdentifier = new Guid("bae477e0-f1ee-4091-8ac8-13fbee2d51ad"),
                            ClientName = "Diego Souza",
                            CreatedAt = new DateTime(2025, 9, 11, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "CreditCard",
                            ServiceName = "Corte",
                            Status = "Paid"
                        },
                        new
                        {
                            IdBilling = 12,
                            Amount = 60.00m,
                            BarberName = "Kauê Olympio",
                            BillingIdentifier = new Guid("7e4705ba-a7a5-4aaf-8208-d98c84198608"),
                            ClientName = "Marcos Paulo",
                            CreatedAt = new DateTime(2025, 9, 12, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Pix",
                            ServiceName = "Corte e Barba",
                            Status = "Paid"
                        },
                        new
                        {
                            IdBilling = 13,
                            Amount = 35.00m,
                            BarberName = "Kauê Olympio",
                            BillingIdentifier = new Guid("f7103f16-5445-4468-ac4e-2bffbb637a4a"),
                            ClientName = "Vinicius Costa",
                            CreatedAt = new DateTime(2025, 9, 13, 10, 35, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Pix",
                            ServiceName = "Corte",
                            Status = "Paid"
                        },
                        new
                        {
                            IdBilling = 14,
                            Amount = 25.00m,
                            BarberName = "Kauê Olympio",
                            BillingIdentifier = new Guid("92b01cac-4e05-4924-815a-f09b1b656346"),
                            ClientName = "Thiago Oliveira",
                            CreatedAt = new DateTime(2025, 9, 14, 15, 45, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Pix",
                            ServiceName = "Barba",
                            Status = "Paid"
                        },
                        new
                        {
                            IdBilling = 15,
                            Amount = 35.00m,
                            BarberName = "Kauê Olympio",
                            BillingIdentifier = new Guid("b57e91e5-2cd2-4a59-9388-adc309be8426"),
                            ClientName = "Paulo Henrique",
                            CreatedAt = new DateTime(2025, 9, 15, 9, 25, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Pix",
                            ServiceName = "Corte",
                            Status = "Paid"
                        },
                        new
                        {
                            IdBilling = 16,
                            Amount = 60.00m,
                            BarberName = "Kauê Olympio",
                            BillingIdentifier = new Guid("3177afda-0617-46db-ac0b-64886b9026d0"),
                            ClientName = "Guilherme Moraes",
                            CreatedAt = new DateTime(2025, 9, 17, 16, 10, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "CreditCard",
                            ServiceName = "Corte e Barba",
                            Status = "Paid"
                        },
                        new
                        {
                            IdBilling = 17,
                            Amount = 35.00m,
                            BarberName = "Kauê Olympio",
                            BillingIdentifier = new Guid("f7cf6b40-71fd-4f6d-8061-0ffb454966ac"),
                            ClientName = "Bruno Ferreira",
                            CreatedAt = new DateTime(2025, 9, 20, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Pix",
                            ServiceName = "Corte",
                            Status = "Paid"
                        },
                        new
                        {
                            IdBilling = 18,
                            Amount = 25.00m,
                            BarberName = "Kauê Olympio",
                            BillingIdentifier = new Guid("7149bad9-45ef-42f1-8e16-9768449d22c8"),
                            ClientName = "Eduardo Nunes",
                            CreatedAt = new DateTime(2025, 9, 24, 15, 55, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Pix",
                            ServiceName = "Barba",
                            Status = "Paid"
                        },
                        new
                        {
                            IdBilling = 19,
                            Amount = 60.00m,
                            BarberName = "Kauê Olympio",
                            BillingIdentifier = new Guid("dddf22ff-d1c3-4709-9c15-97aaa0b119ed"),
                            ClientName = "Rodrigo Martins",
                            CreatedAt = new DateTime(2025, 9, 27, 13, 45, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "CreditCard",
                            ServiceName = "Corte e Barba",
                            Status = "Paid"
                        },
                        new
                        {
                            IdBilling = 20,
                            Amount = 35.00m,
                            BarberName = "Kauê Olympio",
                            BillingIdentifier = new Guid("a1fe27aa-a7ae-472d-b9ff-02826cbc11e7"),
                            ClientName = "Alexandre Souza",
                            CreatedAt = new DateTime(2025, 9, 30, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "CreditCard",
                            ServiceName = "Corte",
                            Status = "Paid"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
